{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aloe.flu",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 6219684,
          "sha512": "eb9b630ce80778fd2f13fbae474aed791fedce5cc838d637a13b591ea6da9161fd3c577da3a97060c832ebd55b54501f9131f6f35da33bca2a4e83029386a588",
          "sha256": "cc263f5040bd3f1469db1b02f5a3a5e88bab19fdd190607834185ade4b096e11",
          "sha1": "6c1930d945092f2f11e2cf172a3c62a23e40ce90",
          "md5": "9736420a6b0ec7f52540a8a87ae675d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 6219684,
          "sha512": "eb9b630ce80778fd2f13fbae474aed791fedce5cc838d637a13b591ea6da9161fd3c577da3a97060c832ebd55b54501f9131f6f35da33bca2a4e83029386a588",
          "sha256": "cc263f5040bd3f1469db1b02f5a3a5e88bab19fdd190607834185ade4b096e11",
          "sha1": "6c1930d945092f2f11e2cf172a3c62a23e40ce90",
          "md5": "9736420a6b0ec7f52540a8a87ae675d6"
        }
      ]
    }
  ]
}
